// src/main/webapp/app/entities/stellar-account/stellar-account.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IStellarAccount } from 'app/shared/model/stellar-account.model';
import { Principal } from 'app/core';
import { StellarAccountService } from './stellar-account.service';

@Component({
    selector: 'jhi-stellar-account',
    templateUrl: './stellar-account.component.html'
})
export class StellarAccountComponent implements OnInit, OnDestroy {
    stellarAccounts: IStellarAccount[];
    currentAccount: any;
    eventSubscriber: Subscription;

    constructor(
        private stellarAccountService: StellarAccountService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private principal: Principal
    ) {}

    loadAll() {
        this.stellarAccountService.query().subscribe(
            (res: HttpResponse<IStellarAccount[]>) => {
                this.stellarAccounts = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInStellarAccounts();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: IStellarAccount) {
        return item.id;
    }

    registerChangeInStellarAccounts() {
        this.eventSubscriber = this.eventManager.subscribe('stellarAccountListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="jBanksterApp.stellarAccount.home.title">Stellar Accounts</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-stellar-account" [routerLink]="['/stellar-account/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="jBanksterApp.stellarAccount.home.createLabel">
            Create new Stellar Account
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="table-responsive" *ngIf="stellarAccounts">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="jBanksterApp.stellarAccount.name">Name</span></th>
            <th><span jhiTranslate="jBanksterApp.stellarAccount.accountId">Account Id</span></th>
            <th><span jhiTranslate="jBanksterApp.stellarAccount.secretSeed">Secret Seed</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let stellarAccount of stellarAccounts ;trackBy: trackId">
                <td><a [routerLink]="['/stellar-account', stellarAccount.id, 'view' ]">{{stellarAccount.id}}</a></td>
                <td>{{stellarAccount.name}}</td>
                <td>{{stellarAccount.accountId}}</td>
                <td>{{stellarAccount.secretSeed}}</td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/stellar-account', stellarAccount.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/stellar-account', stellarAccount.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'stellar-account/'+ stellarAccount.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/stellar-account/stellar-account.tsx
import * as React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import FontAwesomeIcon from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './stellar-account.reducer';
import { IStellarAccount } from 'app/shared/model/stellar-account.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IStellarAccountProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class StellarAccount extends React.Component<IStellarAccountProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { stellarAccountList, match } = this.props;
    return (
      <div>
        <h2 id="stellar-account-heading">
          <Translate contentKey="jbanksterApp.stellarAccount.home.title">Stellar Accounts</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />&nbsp;
            <Translate contentKey="jbanksterApp.stellarAccount.home.createLabel">Create new Stellar Account</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="jbanksterApp.stellarAccount.name">Name</Translate>
                </th>
                <th>
                  <Translate contentKey="jbanksterApp.stellarAccount.accountId">Account Id</Translate>
                </th>
                <th>
                  <Translate contentKey="jbanksterApp.stellarAccount.secretSeed">Secret Seed</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {stellarAccountList.map((stellarAccount, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${stellarAccount.id}`} color="link" size="sm">
                      {stellarAccount.id}
                    </Button>
                  </td>
                  <td>{stellarAccount.name}</td>
                  <td>{stellarAccount.accountId}</td>
                  <td>{stellarAccount.secretSeed}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${stellarAccount.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${stellarAccount.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${stellarAccount.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ stellarAccount }: IRootState) => ({
  stellarAccountList: stellarAccount.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(StellarAccount);
