// src/main/webapp/app/entities/stellar-account/stellar-account-update.tsx
import * as React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import FontAwesomeIcon from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IUserProfile } from 'app/shared/model/user-profile.model';
import { getEntities as getUserProfiles } from 'app/entities/user-profile/user-profile.reducer';
import { getEntity, updateEntity, createEntity, reset } from './stellar-account.reducer';
import { IStellarAccount } from 'app/shared/model/stellar-account.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { keysToValues } from 'app/shared/util/entity-utils';

export interface IStellarAccountUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: number }> {}

export interface IStellarAccountUpdateState {
  isNew: boolean;
  userProfileId: number;
}

export class StellarAccountUpdate extends React.Component<IStellarAccountUpdateProps, IStellarAccountUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      userProfileId: 0,
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getUserProfiles();
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { stellarAccountEntity } = this.props;
      const entity = {
        ...stellarAccountEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
      this.handleClose();
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/stellar-account');
  };

  render() {
    const isInvalid = false;
    const { stellarAccountEntity, userProfiles, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="jbanksterApp.stellarAccount.home.createOrEditLabel">
              <Translate contentKey="jbanksterApp.stellarAccount.home.createOrEditLabel">Create or edit a StellarAccount</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : stellarAccountEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="stellar-account-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="nameLabel" for="name">
                    <Translate contentKey="jbanksterApp.stellarAccount.name">Name</Translate>
                  </Label>
                  <AvField
                    id="stellar-account-name"
                    type="text"
                    name="name"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="accountIdLabel" for="accountId">
                    <Translate contentKey="jbanksterApp.stellarAccount.accountId">Account Id</Translate>
                  </Label>
                  <AvField
                    id="stellar-account-accountId"
                    type="text"
                    name="accountId"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="secretSeedLabel" for="secretSeed">
                    <Translate contentKey="jbanksterApp.stellarAccount.secretSeed">Secret Seed</Translate>
                  </Label>
                  <AvField id="stellar-account-secretSeed" type="text" name="secretSeed" />
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/stellar-account" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />&nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={isInvalid || updating}>
                  <FontAwesomeIcon icon="save" />&nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  userProfiles: storeState.userProfile.entities,
  stellarAccountEntity: storeState.stellarAccount.entity,
  loading: storeState.stellarAccount.loading,
  updating: storeState.stellarAccount.updating
});

const mapDispatchToProps = {
  getUserProfiles,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(StellarAccountUpdate);

// src/main/webapp/app/entities/stellar-account/stellar-account-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { JhiAlertService } from 'ng-jhipster';

import { IStellarAccount } from 'app/shared/model/stellar-account.model';
import { StellarAccountService } from './stellar-account.service';
import { IUserProfile } from 'app/shared/model/user-profile.model';
import { UserProfileService } from 'app/entities/user-profile';

@Component({
    selector: 'jhi-stellar-account-update',
    templateUrl: './stellar-account-update.component.html'
})
export class StellarAccountUpdateComponent implements OnInit {
    private _stellarAccount: IStellarAccount;
    isSaving: boolean;

    userprofiles: IUserProfile[];

    constructor(
        private jhiAlertService: JhiAlertService,
        private stellarAccountService: StellarAccountService,
        private userProfileService: UserProfileService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ stellarAccount }) => {
            this.stellarAccount = stellarAccount;
        });
        this.userProfileService.query().subscribe(
            (res: HttpResponse<IUserProfile[]>) => {
                this.userprofiles = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        if (this.stellarAccount.id !== undefined) {
            this.subscribeToSaveResponse(this.stellarAccountService.update(this.stellarAccount));
        } else {
            this.subscribeToSaveResponse(this.stellarAccountService.create(this.stellarAccount));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<IStellarAccount>>) {
        result.subscribe((res: HttpResponse<IStellarAccount>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackUserProfileById(index: number, item: IUserProfile) {
        return item.id;
    }

    getSelected(selectedVals: Array<any>, option: any) {
        if (selectedVals) {
            for (let i = 0; i < selectedVals.length; i++) {
                if (option.id === selectedVals[i].id) {
                    return selectedVals[i];
                }
            }
        }
        return option;
    }
    get stellarAccount() {
        return this._stellarAccount;
    }

    set stellarAccount(stellarAccount: IStellarAccount) {
        this._stellarAccount = stellarAccount;
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="jhi-stellar-account-heading" jhiTranslate="jBanksterApp.stellarAccount.home.createOrEditLabel">Create or edit a Stellar Account</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!stellarAccount.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="stellarAccount.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="jBanksterApp.stellarAccount.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                        [(ngModel)]="stellarAccount.name" required/>
                    <div [hidden]="!(editForm.controls.name?.dirty && editForm.controls.name?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.name?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="jBanksterApp.stellarAccount.accountId" for="field_accountId">Account Id</label>
                    <input type="text" class="form-control" name="accountId" id="field_accountId"
                        [(ngModel)]="stellarAccount.accountId" required/>
                    <div [hidden]="!(editForm.controls.accountId?.dirty && editForm.controls.accountId?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.accountId?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="jBanksterApp.stellarAccount.secretSeed" for="field_secretSeed">Secret Seed</label>
                    <input type="text" class="form-control" name="secretSeed" id="field_secretSeed"
                        [(ngModel)]="stellarAccount.secretSeed" />
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
