// src/main/webapp/app/entities/stellar-account/stellar-account-detail.tsx
import * as React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import FontAwesomeIcon from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './stellar-account.reducer';
import { IStellarAccount } from 'app/shared/model/stellar-account.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IStellarAccountDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: number }> {}

export class StellarAccountDetail extends React.Component<IStellarAccountDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { stellarAccountEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="jbanksterApp.stellarAccount.detail.title">StellarAccount</Translate> [<b>{stellarAccountEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="name">
                <Translate contentKey="jbanksterApp.stellarAccount.name">Name</Translate>
              </span>
            </dt>
            <dd>{stellarAccountEntity.name}</dd>
            <dt>
              <span id="accountId">
                <Translate contentKey="jbanksterApp.stellarAccount.accountId">Account Id</Translate>
              </span>
            </dt>
            <dd>{stellarAccountEntity.accountId}</dd>
            <dt>
              <span id="secretSeed">
                <Translate contentKey="jbanksterApp.stellarAccount.secretSeed">Secret Seed</Translate>
              </span>
            </dt>
            <dd>{stellarAccountEntity.secretSeed}</dd>
          </dl>
          <Button tag={Link} to="/entity/stellar-account" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>&nbsp;
          <Button tag={Link} to={`/entity/stellar-account/${stellarAccountEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ stellarAccount }: IRootState) => ({
  stellarAccountEntity: stellarAccount.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(StellarAccountDetail);

// src/main/webapp/app/entities/stellar-account/stellar-account-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IStellarAccount } from 'app/shared/model/stellar-account.model';

@Component({
    selector: 'jhi-stellar-account-detail',
    templateUrl: './stellar-account-detail.component.html'
})
export class StellarAccountDetailComponent implements OnInit {
    stellarAccount: IStellarAccount;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ stellarAccount }) => {
            this.stellarAccount = stellarAccount;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="stellarAccount">
            <h2><span jhiTranslate="jBanksterApp.stellarAccount.detail.title">Stellar Account</span> {{stellarAccount.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="jBanksterApp.stellarAccount.name">Name</span></dt>
                <dd>
                    <span>{{stellarAccount.name}}</span>
                </dd>
                <dt><span jhiTranslate="jBanksterApp.stellarAccount.accountId">Account Id</span></dt>
                <dd>
                    <span>{{stellarAccount.accountId}}</span>
                </dd>
                <dt><span jhiTranslate="jBanksterApp.stellarAccount.secretSeed">Secret Seed</span></dt>
                <dd>
                    <span>{{stellarAccount.secretSeed}}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/stellar-account', stellarAccount.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>
